# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_create_database(object):
    def setupUi(self, create_database):
        create_database.setObjectName("create_database")
        create_database.resize(245, 94)
        self.pushButton = QtWidgets.QPushButton(create_database)
        self.pushButton.setGeometry(QtCore.QRect(90, 60, 71, 32))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(create_database)
        self.widget.setGeometry(QtCore.QRect(16, 11, 191, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)

        self.retranslateUi(create_database)
        QtCore.QMetaObject.connectSlotsByName(create_database)

    def retranslateUi(self, create_database):
        _translate = QtCore.QCoreApplication.translate
        create_database.setWindowTitle(_translate("create_database", "创建数据库"))
        self.pushButton.setText(_translate("create_database", "创建"))
        self.label.setText(_translate("create_database", "数据库名:"))
