# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '456.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(398, 283)
        Form.setMinimumSize(QtCore.QSize(398, 283))
        Form.setMaximumSize(QtCore.QSize(398, 283))
        self.address = QtWidgets.QLineEdit(Form)
        self.address.setGeometry(QtCore.QRect(120, 70, 171, 21))
        self.address.setToolTipDuration(-1)
        self.address.setCursorPosition(0)
        self.address.setObjectName("address")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(120, 30, 251, 21))
        self.name.setToolTipDuration(-1)
        self.name.setObjectName("name")
        self.user = QtWidgets.QLineEdit(Form)
        self.user.setGeometry(QtCore.QRect(120, 110, 251, 21))
        self.user.setObjectName("user")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 81, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 81, 16))
        self.label_3.setToolTipDuration(-1)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setIndent(0)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 230, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 230, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(290, 70, 21, 16))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 30, 81, 16))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.password = QtWidgets.QLineEdit(Form)
        self.password.setGeometry(QtCore.QRect(120, 150, 251, 21))
        self.password.setObjectName("password")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.port = QtWidgets.QSpinBox(Form)
        self.port.setGeometry(QtCore.QRect(310, 70, 71, 21))
        self.port.setMaximum(65536)
        self.port.setValue(8086)
        self.port.setObjectName("port")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 190, 81, 16))
        self.label_6.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setGeometry(QtCore.QRect(120, 190, 87, 20))
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.name, self.address)
        Form.setTabOrder(self.address, self.port)
        Form.setTabOrder(self.port, self.user)
        Form.setTabOrder(self.user, self.password)
        Form.setTabOrder(self.password, self.checkBox)
        Form.setTabOrder(self.checkBox, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "新建连接"))
        self.label.setText(_translate("Form", "服务器地址："))
        self.label_2.setText(_translate("Form", "密码："))
        self.label_3.setText(_translate("Form", "账号："))
        self.pushButton.setText(_translate("Form", "保存"))
        self.pushButton_2.setText(_translate("Form", "测试"))
        self.label_4.setText(_translate("Form", ":"))
        self.label_5.setText(_translate("Form", "名称："))
        self.label_6.setText(_translate("Form", "安全："))
        self.checkBox.setText(_translate("Form", " 使用SSL"))
