"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
APP_NAME = "InfluxDBClient"
DATA_FILES = ['main.py', 'create_database.py', 'create_ui.py', 'history_ui.py', 'new_connect_ui.py', 'ui.py', 'db',
              'images']
OPTIONS = {'iconfile': 'main.icns'}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
