# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '123.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import *


class MyTableWidget(QtWidgets.QTableWidget):
    def __init__(self, centralwidget):
        super(MyTableWidget, self).__init__(centralwidget)

        self.nCurScroller = 0  # 翻页时的当时滑动条位置
        self.pageValue = 10  # 一页显示条数
        self.create_form()

    def create_form(self):
        pass
        # self.horizontalHeader().setVisible(False)  # 隐藏水平表头
        # self.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked)  # 双击编辑
        # self.horizontalHeader().setResizeMode(QtGui.QHeaderView.ResizeToContents)
        # self.verticalHeader().setResizeMode(QtGui.QHeaderView.ResizeToContents)

    def pre_page(self):

        max_value = self.verticalScrollBar().maximum()  # 当前SCROLLER最大显示值
        self.nCurScroller = self.verticalScrollBar().value()  # 获得当前scroller值

        if self.nCurScroller > 0:
            self.verticalScrollBar().setSliderPosition(self.nCurScroller - self.pageValue)
        else:
            self.verticalScrollBar().setSliderPosition(max_value)

    def next_page(self):

        # verticalScrollBar().setSliderPosition()  设置当前滑动条的位置
        # verticalScrollBar().maximum()            滑动条能移动的最大位置
        # verticalScrollBar().value()                  获得当前滑动条的位置
        max_value = self.verticalScrollBar().maximum()  # 当前SCROLLER最大显示值
        self.nCurScroller = self.verticalScrollBar().value()  # 获得当前scroller值

        if self.nCurScroller < max_value:
            self.verticalScrollBar().setSliderPosition(self.pageValue + self.nCurScroller)
        else:
            self.verticalScrollBar().setSliderPosition(0)


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1416, 900)
        MainWindow.setMinimumSize(QtCore.QSize(1416, 900))
        MainWindow.setMaximumSize(QtCore.QSize(1416, 900))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeView = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeView.setGeometry(QtCore.QRect(20, 20, 281, 800))
        self.treeView.setObjectName("treeView")
        self.treeView.setColumnCount(2)  # 设置列数
        self.treeView.setHeaderLabels(["服务器", "value"])  # 设置标题头
        self.treeView.setHeaderHidden(True)  # 隐藏标题
        self.treeView.setColumnHidden(1, True)  # 隐藏vlue列
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(310, 20, 1101, 850))
        font = QtGui.QFont()
        font.setKerning(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        self.execAction = QAction(QIcon("images/exec.ico"), "运行", self.toolBar)
        self.history_button = QAction(QIcon("images/history.ico"), "历史命令", self.toolBar)
        self.toolBar.addAction(self.execAction)
        self.toolBar.addAction(self.history_button)
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1416, 22))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.actionxinjian = QtWidgets.QAction(MainWindow)
        self.actionxinjian.setObjectName("actionxinjian")
        self.menu.addAction(self.actionxinjian)
        self.menuBar.addAction(self.menu.menuAction())
        self.retranslateUi(MainWindow)
        # self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "InfluxDB"))
        # self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionxinjian.setText(_translate("MainWindow", "新建连接"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
